<?php
declare(strict_types=1);
/*
 * Uso ÚNICO. Cria a tabela "jd_catalog_items" (catálogo do site do Professor
 * Jorge Dadalt: livros/e-books, cursos/mentorias, negócios digitais) e adiciona
 * a coluna "site" em "contacts", em bancos que já foram instalados antes desta
 * função existir. Se o banco for instalado do zero via /install.php, tudo isso
 * já é criado automaticamente pelo schema — este script não é necessário.
 *
 * Também insere (uma vez, ON CONFLICT DO NOTHING) os 14 itens de catálogo com
 * o texto hoje publicado no site do Jorge Dadalt, para a migração não perder
 * conteúdo.
 *
 * Exige login no /admin/. Depois de rodar (uma vez), APAGUE este arquivo.
 */
require_once __DIR__ . '/app/auth.php';
require_admin();
header('Content-Type: text/plain; charset=utf-8');

$pdo = db();
$sql = <<<SQL
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS site VARCHAR(20) NOT NULL DEFAULT 'gib';

-- Catálogo do site do Professor Jorge Dadalt (livros/e-books, cursos/mentorias,
-- negócios digitais), gerenciado neste mesmo admin e servido via api/jd-catalog.php.
CREATE TABLE IF NOT EXISTS jd_catalog_items (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category VARCHAR(30) NOT NULL CHECK (category IN ('livros-e-ebooks','cursos-e-mentorias','negocios-digitais')),
  item_type VARCHAR(20) NOT NULL CHECK (item_type IN ('livro','ebook','curso','mentoria','negocio')),
  slug VARCHAR(120) NOT NULL UNIQUE,
  url_slug VARCHAR(120) NOT NULL,
  type_label VARCHAR(60) NOT NULL DEFAULT '',
  title VARCHAR(220) NOT NULL,
  image_url VARCHAR(500),
  headline TEXT,
  lead TEXT,
  list_summary VARCHAR(400),
  points JSONB NOT NULL DEFAULT '[]'::jsonb,
  price VARCHAR(80),
  cta_label VARCHAR(60) NOT NULL DEFAULT 'Saiba mais',
  cta_href VARCHAR(500) NOT NULL,
  trust JSONB NOT NULL DEFAULT '[]'::jsonb,
  question TEXT,
  story JSONB NOT NULL DEFAULT '[]'::jsonb,
  outcomes JSONB NOT NULL DEFAULT '[]'::jsonb,
  audience JSONB NOT NULL DEFAULT '[]'::jsonb,
  format_label VARCHAR(120),
  format_answer TEXT,
  stakes TEXT,
  journey JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'published' CHECK (status IN ('draft','published')),
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_jd_catalog_category_status ON jd_catalog_items (category, status, sort_order);
CREATE INDEX IF NOT EXISTS idx_jd_catalog_type ON jd_catalog_items (item_type);

INSERT INTO jd_catalog_items (category, item_type, slug, url_slug, type_label, title, image_url, headline, lead, list_summary, points, price, cta_label, cta_href, trust, question, story, outcomes, audience, format_label, format_answer, stakes, journey) VALUES
('livros-e-ebooks', 'livro', 'livro-trabalhe-pouco', 'livro-trabalhe-pouco', 'Livro físico', 'Trabalhe Pouco, Ganhe Muito', '/images/livro-trabalhe-pouco-ganhe-muito.png', 'Talvez você não precise trabalhar mais. Precise trabalhar com <em>mais inteligência</em>.', 'Uma obra construída a partir de décadas de experiência real para repensar esforço, tempo, tecnologia, resultados e liberdade.', 'Estratégia, tecnologia, disciplina e propósito para produzir mais resultado sem entregar toda a vida ao trabalho.', '["Reavalie a relação entre esforço, tempo e resultado","Use estratégia, disciplina e tecnologia a seu favor","Construa autonomia financeira e geográfica com responsabilidade"]'::jsonb, 'R$ 59,90', 'Quero meu livro', 'https://pay.hotmart.com/A107107275M', '[["01","Estratégia antes do esforço","Mais direção para suas escolhas"],["02","Experiência real","Aprendizados de uma trajetória empresarial"],["03","Liberdade com responsabilidade","Autonomia construída com método"]]'::jsonb, 'Quanto da sua vida está sendo consumido por uma rotina que não leva você adiante?', '["Trabalhar muito virou sinônimo de mérito. Mas horas acumuladas não garantem clareza, prosperidade ou liberdade. Sem direção, o esforço pode apenas manter você ocupado — e distante da vida que deseja construir.","Este livro propõe substituir o automatismo por escolhas conscientes e transformar conhecimento, tecnologia e disciplina em instrumentos de autonomia."]'::jsonb, '[["01","Trabalhar com direção","Organize prioridades e concentre energia no que realmente produz resultado."],["02","Usar melhor a tecnologia","Transforme ferramentas digitais em alavancas de produtividade e liberdade."],["03","Construir uma vida sustentável","Equilibre trabalho, propósito, recursos e tempo sem promessas fáceis."]]'::jsonb, '["Empresários cansados de confundir excesso de trabalho com progresso","Profissionais que desejam mais autonomia e clareza","Pessoas em transição para uma vida profissional digital","Leitores que valorizam experiência prática e pensamento crítico"]'::jsonb, 'Livro físico • edição especial', 'Esta página apresenta o livro físico, enviado após a confirmação da compra.', NULL, '[]'::jsonb),
('livros-e-ebooks', 'livro', 'livro-da-ideia-ao-lucro', 'livro-da-ideia-ao-lucro', 'Livro físico', 'Da Ideia ao Lucro', '/images/livro-da-ideia-ao-lucro.png', 'Faturar muito não significa <em>lucrar bem</em>.', 'Um método prático para analisar a viabilidade do negócio, identificar oportunidades de melhoria e tomar decisões empresariais mais seguras.', 'Um método prático para descobrir se o negócio realmente produz lucro ou apenas movimenta dinheiro.', '["Separe faturamento de lucro verdadeiro","Entenda custos, margem e rentabilidade","Decida com critérios antes de investir, crescer ou recuar"]'::jsonb, 'Informações e lançamento', 'Quero conhecer o livro', '/contato?assunto=livro-da-ideia-ao-lucro', '[["01","Diagnóstico","Veja o negócio como ele realmente é"],["02","Método","Organize números e decisões"],["03","Clareza","Saiba o que corrigir antes de crescer"]]'::jsonb, 'Sua empresa produz lucro ou apenas movimenta dinheiro?', '["Muitos negócios vendem, empregam pessoas e mantêm uma rotina intensa, mas não conseguem revelar com precisão quanto realmente deixam para o proprietário.","Da Ideia ao Lucro organiza essa análise em uma linguagem direta, conectando números, operação e decisão para que o empresário compreenda o que sustenta — e o que drena — seus resultados."]'::jsonb, '[["01","Enxergar o lucro real","Diferencie caixa, faturamento, margem e resultado líquido."],["02","Avaliar a viabilidade","Entenda se o modelo se sustenta no presente e no longo prazo."],["03","Decidir com segurança","Identifique quando corrigir, reposicionar, investir ou crescer."]]'::jsonb, '["Empreendedores que ainda misturam finanças pessoais e empresariais","Empresas com vendas, mas pouca sobra de caixa","Quem está validando uma nova ideia de negócio","Gestores que precisam transformar dados em decisões"]'::jsonb, 'Livro físico • conteúdo aplicado', 'Esta página apresenta a edição física do livro. As condições de lançamento são informadas pelo contato.', NULL, '[]'::jsonb),
('livros-e-ebooks', 'livro', 'livro-maior-patrimonio', 'livro-o-seu-maior-patrimonio', 'Livro físico', 'O Seu Maior Patrimônio', '/images/livro-o-seu-maior-patrimonio.png', 'O patrimônio mais importante é a vida que você consegue sustentar com <em>saúde e propósito</em>.', 'Uma reflexão prática sobre os hábitos que protegem sua saúde, sua energia e sua qualidade de vida ao longo dos anos.', 'Uma reflexão sobre os hábitos que sustentam saúde, energia, equilíbrio e qualidade de vida ao longo dos anos.', '["Compreenda saúde como base de todas as conquistas","Construa hábitos possíveis e sustentáveis","Integre vitalidade, equilíbrio financeiro e plenitude emocional"]'::jsonb, 'Informações e lançamento', 'Quero conhecer o livro', '/contato?assunto=livro-o-seu-maior-patrimonio', '[["01","Vitalidade","Energia para viver e realizar"],["02","Equilíbrio","Decisões coerentes com a vida real"],["03","Propósito","Um patrimônio que atravessa os anos"]]'::jsonb, 'De que vale construir tudo, se você não preservar a capacidade de viver bem?', '["Patrimônio não se resume a bens, empresas ou investimentos. Corpo são, estabilidade financeira e plenitude emocional formam uma base inseparável para uma vida verdadeiramente próspera.","O livro convida o leitor a rever escolhas cotidianas e a reconhecer que longevidade com qualidade é construída de forma consciente, um hábito de cada vez."]'::jsonb, '[["01","Rever prioridades","Reconheça o que realmente sustenta uma vida longa e significativa."],["02","Proteger sua energia","Observe hábitos que fortalecem ou enfraquecem seu cotidiano."],["03","Viver com propósito","Alinhe saúde, equilíbrio e escolhas de longo prazo."]]'::jsonb, '["Pessoas que desejam envelhecer com autonomia","Profissionais que negligenciaram a saúde pela rotina","Leitores em busca de equilíbrio sem fórmulas milagrosas","Famílias que querem construir hábitos melhores juntas"]'::jsonb, 'Livro físico • experiência e reflexão', 'Esta página apresenta a edição física do livro. As informações de disponibilidade são fornecidas pelo contato.', NULL, '[]'::jsonb),
('livros-e-ebooks', 'ebook', 'ebook-trabalhe-pouco', 'ebook-trabalhe-pouco', 'E-book', 'Trabalhe Pouco, Ganhe Muito', '/images/ebook-trabalhe-pouco-ganhe-muito.png', 'Menos esforço desperdiçado. Mais liberdade. <em>Mais vida.</em>', 'Uma leitura digital para transformar tecnologia, disciplina, automação e propósito em uma forma mais inteligente de trabalhar.', 'Uma nova relação entre trabalho, tecnologia, automação, liberdade financeira e liberdade geográfica.', '["Identifique atividades que consomem tempo sem gerar valor","Use automação e tecnologia com critério","Construa liberdade financeira e geográfica de forma responsável"]'::jsonb, 'Edição digital', 'Quero conhecer o e-book', '/contato?assunto=ebook-trabalhe-pouco-ganhe-muito', '[["01","Leitura imediata","Acesso digital em diferentes dispositivos"],["02","Aplicação prática","Reflexões conectadas ao cotidiano"],["03","Nova mentalidade","Resultado acima da ocupação"]]'::jsonb, 'Você está construindo liberdade ou apenas ficando cada vez mais ocupado?', '["A era digital criou ferramentas capazes de ampliar produtividade e alcance, mas também multiplicou distrações, urgências e trabalhos sem impacto.","Este e-book ajuda o leitor a reorganizar sua relação com o trabalho, usando inteligência, disciplina e tecnologia para produzir resultados sem entregar toda a vida à rotina."]'::jsonb, '[["01","Eliminar desperdícios","Reconheça tarefas que ocupam muito e entregam pouco."],["02","Criar sistemas","Estruture processos que não dependam exclusivamente da sua presença."],["03","Recuperar tempo","Transforme eficiência em autonomia e qualidade de vida."]]'::jsonb, '["Profissionais que desejam trabalhar de qualquer lugar","Empreendedores sobrecarregados pela operação","Criadores e gestores de negócios digitais","Quem busca produtividade com propósito"]'::jsonb, 'E-book digital • leitura em celular, tablet ou computador', 'É uma edição digital preparada para leitura em celular, tablet ou computador.', NULL, '[]'::jsonb),
('livros-e-ebooks', 'ebook', 'ebook-da-ideia-ao-lucro', 'ebook-da-ideia-ao-lucro', 'E-book', 'Da Ideia ao Lucro', '/images/ebook-da-ideia-ao-lucro.png', 'Descubra se o seu negócio realmente dá lucro — ou apenas <em>gera faturamento</em>.', 'Um diagnóstico guiado para organizar números, avaliar a viabilidade e tomar decisões melhores com os dados do próprio negócio.', 'Organize os números da empresa, avalie sua viabilidade e decida com mais segurança.', '["Organize a realidade financeira da empresa","Identifique o que sustenta e o que consome resultados","Decida se é hora de corrigir, reposicionar ou crescer"]'::jsonb, 'Edição digital', 'Quero conhecer o método', '/contato?assunto=ebook-da-ideia-ao-lucro', '[["01","Seus números","O diagnóstico parte da sua realidade"],["02","Passo a passo","Análise clara, organizada e aplicável"],["03","Decisão","Critério antes de novos investimentos"]]'::jsonb, 'Em que dia do mês sua empresa termina de pagar os outros e começa a trabalhar para você?', '["Venda não é lucro. Movimento não é resultado. E uma empresa ocupada pode continuar escondendo custos, margens insuficientes e decisões tomadas apenas pela intuição.","O método Da Ideia ao Lucro orienta o leitor a organizar informações e enxergar o negócio com mais objetividade, sem fórmulas prontas e sem promessas financeiras."]'::jsonb, '[["01","Lucro de verdade","Entenda a diferença entre dinheiro entrando e resultado existindo."],["02","Viabilidade no longo prazo","Avalie se a empresa se sustenta ou depende do seu sacrifício."],["03","Crescimento com critério","Saiba quando investir, contratar, corrigir ou esperar."]]'::jsonb, '["Quem está começando um negócio","Empresários que vendem, mas não veem dinheiro sobrar","Gestores que precisam organizar custos e margens","Quem deseja validar uma ideia antes de investir mais"]'::jsonb, 'E-book digital • método de diagnóstico', 'É um material digital para leitura e aplicação no próprio ritmo, usando os dados do seu negócio.', NULL, '[]'::jsonb),
('livros-e-ebooks', 'ebook', 'ebook-maior-patrimonio', 'ebook-o-seu-maior-patrimonio', 'E-book', 'O Seu Maior Patrimônio', '/images/ebook-o-seu-maior-patrimonio.png', 'Saúde, energia e qualidade de vida: o patrimônio que nenhum dinheiro consegue <em>substituir</em>.', 'Uma jornada digital de reflexão e aplicação prática para construir hábitos que protegem sua vitalidade ao longo dos anos.', 'Hábitos e escolhas para proteger vitalidade, energia e qualidade de vida no longo prazo.', '["Reavalie hábitos que afetam sua energia diária","Conecte saúde física, equilíbrio financeiro e bem-estar emocional","Faça escolhas sustentáveis, sem promessas ou soluções mágicas"]'::jsonb, 'Edição digital', 'Quero conhecer o e-book', '/contato?assunto=ebook-o-seu-maior-patrimonio', '[["01","Consciência","Entenda o impacto das escolhas diárias"],["02","Constância","Pequenas atitudes sustentadas no tempo"],["03","Qualidade de vida","Autonomia para aproveitar suas conquistas"]]'::jsonb, 'Você está cuidando do patrimônio que sustenta todos os demais?', '["O corpo é a estrutura que carrega cada projeto, relacionamento e conquista. Quando saúde, energia e equilíbrio são deixados para depois, todo o restante se torna mais frágil.","O Seu Maior Patrimônio reúne experiência, reflexão e propósito para ajudar o leitor a olhar para a própria vida com mais responsabilidade e visão de longo prazo."]'::jsonb, '[["01","Observar seus hábitos","Identifique escolhas que favorecem ou comprometem sua vitalidade."],["02","Integrar os pilares","Conecte corpo, finanças e equilíbrio emocional."],["03","Pensar no longo prazo","Construa uma vida que continue valendo a pena ao longo dos anos."]]'::jsonb, '["Adultos que querem envelhecer com autonomia","Pessoas em busca de hábitos sustentáveis","Profissionais que precisam recuperar equilíbrio","Leitores que valorizam experiência real e propósito"]'::jsonb, 'E-book digital • leitura reflexiva e prática', 'É uma edição digital, acessível em celular, tablet ou computador.', NULL, '[]'::jsonb),
('cursos-e-mentorias', 'curso', 'curso-gestao-online', 'gestao-de-negocios-online', 'Curso online', 'Gestão de Negócios Online', '/images/curso-novo.png', 'Transforme conhecimento e esforço em um negócio digital <em>organizado e rentável</em>.', 'Uma formação completa para planejar, estruturar, automatizar e desenvolver negócios online com método, indicadores e decisões conscientes.', 'Uma formação completa para planejar, estruturar, automatizar e desenvolver negócios online.', '["Construa uma proposta de valor clara e vendável","Organize operação, marketing, finanças e tecnologia","Use automação e inteligência artificial para ganhar eficiência"]'::jsonb, NULL, 'Comprar', '/contato?assunto=curso-gestao-de-negocios-online', '[]'::jsonb, 'Seu negócio digital tem método — ou depende de improviso todos os dias?', '["A internet abre oportunidades, mas não substitui planejamento. Sem posicionamento, processos e controle, boas ideias perdem força antes de produzir resultados.","Esta formação reúne fundamentos de gestão e ferramentas atuais para conduzir o aluno do diagnóstico à execução, com uma visão integrada do negócio."]'::jsonb, '[["01","Direção estratégica","Defina público, oferta, canais e objetivos coerentes."],["02","Operação organizada","Crie processos que reduzam retrabalho e dependência."],["03","Crescimento sustentável","Acompanhe indicadores antes de ampliar investimentos."]]'::jsonb, '["Quem deseja iniciar um negócio online com bases sólidas","Empreendedores digitais que perderam o controle da operação","Profissionais que querem transformar conhecimento em oferta","Gestores que buscam eficiência com tecnologia e IA"]'::jsonb, NULL, NULL, NULL, '[]'::jsonb),
('cursos-e-mentorias', 'mentoria', 'mentoria-1', 'meu-primeiro-negocio', 'Mentoria 01', 'Meu Primeiro Negócio', '/images/mentoria-1-meu-primeiro-negocio.png', 'Sua ideia pode continuar apenas no papel — ou ganhar um caminho seguro até a <em>primeira venda</em>.', 'Uma mentoria para transformar insegurança em direção: valide a oportunidade, construa uma oferta clara e avance com um plano possível para os próximos 90 dias.', 'Da ideia à primeira estrutura comercial, com validação, oferta e plano para os primeiros 90 dias.', '["Defina problema, público e proposta de valor","Valide antes de comprometer tempo e dinheiro","Estruture oferta, canais e primeiras vendas"]'::jsonb, NULL, 'Conhecer', '/contato?assunto=mentoria-meu-primeiro-negocio', '[]'::jsonb, 'Quanto custa continuar adiando uma ideia que pode mudar sua trajetória profissional?', '["Muitas boas ideias não fracassam por falta de potencial, mas por excesso de dúvidas, tentativas dispersas e medo de escolher o caminho errado. Quando tudo parece prioridade, nada realmente avança.","Nesta mentoria, você organiza a decisão antes de ampliar o risco. Juntos, traduzimos sua experiência em proposta de valor, testamos a aderência ao mercado e definimos ações concretas para sair da intenção e chegar à primeira venda."]'::jsonb, '[["01","Coragem com direção","Substitua a ansiedade de começar por critérios claros de decisão."],["02","Oferta validada","Descubra o que o público valoriza antes de investir mais tempo e dinheiro."],["03","Primeiros 90 dias","Tenha prioridades, marcos e próximos passos que cabem na sua realidade."]]'::jsonb, '["Pessoas com uma ideia, mas sem roteiro de execução","Profissionais que desejam empreender pela primeira vez","Especialistas que querem transformar conhecimento em negócio","Quem prefere validar antes de assumir riscos maiores"]'::jsonb, NULL, NULL, 'Você não precisa esperar sentir certeza absoluta. Precisa de clareza suficiente para dar o próximo passo certo.', '[["1","Diagnosticar","Sua experiência, seus recursos e a oportunidade real."],["2","Validar","Público, problema, proposta e disposição de compra."],["3","Estruturar","Oferta, canais, rotina e plano de ação."],["4","Avançar","Primeiras conversas comerciais e ajustes orientados."]]'::jsonb),
('cursos-e-mentorias', 'mentoria', 'mentoria-2', 'organizando-meu-negocio', 'Mentoria 02', 'Organizando Meu Negócio', '/images/mentoria-2-organizando-meu-negocio.png', 'Recupere o controle do seu negócio antes que a desorganização controle <em>você</em>.', 'Uma mentoria para quem vende, trabalha muito e ainda sente que a empresa depende de memória, urgências e esforço pessoal. Organize processos, finanças e gestão para voltar a decidir com tranquilidade.', 'Processos, finanças, responsabilidades e indicadores para crescer com controle.', '["Enxergue custos, margens, caixa e resultados","Organize processos e responsabilidades","Construa uma rotina de gestão baseada em indicadores"]'::jsonb, NULL, 'Conhecer', '/contato?assunto=mentoria-organizando-meu-negocio', '[]'::jsonb, 'Seu negócio está construindo liberdade — ou apenas uma rotina cada vez mais pesada?', '["Quando cada venda traz novas urgências, o crescimento deixa de ser motivo de orgulho e passa a ser fonte de desgaste. Falta de números confiáveis, tarefas sem responsáveis e decisões tomadas no improviso consomem energia e margem.","A mentoria transforma essa pressão em um sistema de gestão compreensível. Identificamos gargalos, organizamos responsabilidades e criamos uma rotina de acompanhamento para que você volte a enxergar o negócio por inteiro."]'::jsonb, '[["01","Alívio operacional","Reduza retrabalho e pare de carregar todas as decisões sozinho."],["02","Segurança financeira","Entenda caixa, custos, preços e margens antes de agir."],["03","Gestão visível","Acompanhe poucos indicadores úteis e corrija a rota no tempo certo."]]'::jsonb, '["Empresas com vendas, mas pouca previsibilidade","Empreendedores sobrecarregados pela operação","Negócios com finanças e processos desorganizados","Gestores que precisam recuperar controle antes de crescer"]'::jsonb, NULL, NULL, 'Organizar não é burocratizar. É criar espaço para pensar, liderar e crescer sem viver apagando incêndios.', '[["1","Mapear","Processos, números, equipe e principais pontos de pressão."],["2","Priorizar","O que precisa ser corrigido primeiro para recuperar controle."],["3","Organizar","Responsabilidades, rotinas e indicadores essenciais."],["4","Consolidar","Um sistema de gestão que continue funcionando no dia a dia."]]'::jsonb),
('cursos-e-mentorias', 'mentoria', 'mentoria-3', 'escalando-meu-negocio', 'Mentoria 03', 'Escalando Meu Negócio', '/images/mentoria-3-escalando-meu-negocio.png', 'Seu negócio já provou que funciona. Agora ele precisa crescer sem perder <em>qualidade, margem e identidade</em>.', 'Uma mentoria para transformar tração em escala sustentável, removendo gargalos, fortalecendo a operação e escolhendo os canais que realmente merecem investimento.', 'Estratégia, automação e capacidade operacional para ampliar resultados com segurança.', '["Identifique o que limita o crescimento","Estruture metas, equipe, sistemas e automações","Amplie vendas sem comprometer qualidade e margem"]'::jsonb, NULL, 'Conhecer', '/contato?assunto=mentoria-escalando-meu-negocio', '[]'::jsonb, 'Se as vendas dobrarem amanhã, sua empresa estará pronta — ou os problemas também dobrarão?', '["Crescer rápido sobre uma base frágil aumenta atrasos, custos, conflitos e perda de qualidade. O próximo nível exige mais do que ambição: exige capacidade operacional, critérios e decisões sustentadas por dados.","Nesta mentoria, identificamos o limite atual do negócio, desenhamos prioridades de expansão e alinhamos equipe, automações, canais e indicadores para que o crescimento fortaleça — e não ameace — o que já foi conquistado."]'::jsonb, '[["01","Foco estratégico","Concentre recursos nas oportunidades com melhor potencial e aderência."],["02","Capacidade de escala","Automatize o repetitivo e fortaleça processos críticos."],["03","Crescimento saudável","Amplie receita acompanhando margem, qualidade e experiência do cliente."]]'::jsonb, '["Negócios com produto ou serviço já validado","Empresas que atingiram um limite operacional","Gestores que querem ampliar canais e mercados","Empreendedores que desejam crescer com critérios"]'::jsonb, NULL, NULL, 'Escala não é correr mais. É construir uma empresa capaz de ir mais longe sem depender de esforço heroico todos os dias.', '[["1","Diagnosticar","O gargalo que hoje limita vendas, entrega ou rentabilidade."],["2","Projetar","Metas, capacidade, equipe e investimentos necessários."],["3","Automatizar","Rotinas que podem ganhar velocidade e consistência."],["4","Escalar","Canais e ações acompanhados por indicadores claros."]]'::jsonb),
('cursos-e-mentorias', 'mentoria', 'mentoria-4', 'blindagem-patrimonial', 'Mentoria 04', 'Blindagem Patrimonial', '/images/mentoria-4-blindagem-patrimonial.png', 'O patrimônio de uma vida merece mais do que esperança: merece <em>governança, continuidade e proteção</em>.', 'Uma mentoria estratégica e educacional para empresários e famílias que desejam organizar riscos, alinhar sucessão e preservar o valor construído ao longo de décadas.', 'Governança, sucessão e organização estratégica para patrimônios consolidados.', '["Mapeie riscos pessoais, empresariais e sucessórios","Organize estruturas e responsabilidades com governança","Planeje continuidade familiar e societária"]'::jsonb, NULL, 'Conhecer', '/contato?assunto=mentoria-blindagem-patrimonial', '[]'::jsonb, 'Se uma mudança inesperada acontecer hoje, sua família e suas empresas saberão exatamente como continuar?', '["Patrimônio não é apenas um conjunto de bens. Ele representa trabalho, escolhas, responsabilidades e o futuro de pessoas que dependem dessa estrutura. Sem planejamento, decisões urgentes podem gerar conflitos, custos e perda de continuidade.","A mentoria cria visão integrada e coordena as perguntas certas para que profissionais jurídicos, contábeis e financeiros possam atuar com propósito comum. Você sai com clareza sobre riscos, prioridades e próximos passos — sem soluções genéricas."]'::jsonb, '[["01","Tranquilidade estratégica","Enxergue vulnerabilidades antes que se tornem crises."],["02","Continuidade familiar","Prepare sucessão, papéis e decisões com diálogo e método."],["03","Governança patrimonial","Organize ativos, empresas e responsabilidades com visão de longo prazo."]]'::jsonb, '["Empresários com patrimônio pessoal e empresarial integrado","Famílias que precisam planejar sucessão","Sócios que desejam regras claras de continuidade","Empreendedores com operações nacionais e internacionais"]'::jsonb, NULL, NULL, 'Planejar cedo preserva escolhas. Adiar pode obrigar a família a decidir sob pressão justamente quando mais precisa de segurança.', '[["1","Mapear","Patrimônio, estruturas, riscos e relações relevantes."],["2","Alinhar","Objetivos pessoais, familiares e empresariais."],["3","Coordenar","Prioridades com apoio jurídico, contábil e financeiro."],["4","Proteger","Plano de continuidade, governança e revisão periódica."]]'::jsonb),
('negocios-digitais', 'negocio', 'sites', 'criacao-de-sites', 'Solução digital', 'Criação de Sites Profissionais', '/images/negocio-criacao-de-sites.png', 'Seu site não deve apenas existir. Deve <em>fortalecer sua marca e gerar oportunidades</em>.', 'Planejamento, conteúdo, design responsivo e estrutura técnica para transformar sua presença digital em um ativo comercial.', 'Uma plataforma profissional para fortalecer sua marca, apresentar valor e gerar oportunidades.', '["Posicionamento e mensagem alinhados ao seu público","Experiência profissional em computador e celular","Estrutura preparada para campanhas e conversões"]'::jsonb, NULL, 'Conhecer', '/contato?assunto=projeto-criacao-de-site', '[]'::jsonb, 'Quando um cliente procura sua empresa, o seu site confirma a confiança — ou cria novas dúvidas?', '["O site é frequentemente o primeiro contato sério entre uma empresa e seu futuro cliente. Aparência improvisada, mensagens vagas e navegação confusa reduzem credibilidade.","Construímos uma presença digital coerente com os objetivos do negócio, combinando clareza comercial, design e tecnologia."]'::jsonb, '[["01","Autoridade","Uma apresentação compatível com a qualidade da empresa."],["02","Conversão","Caminhos claros para contato, orçamento ou compra."],["03","Base digital","Estrutura preparada para conteúdo, anúncios e evolução."]]'::jsonb, '["Empresas que ainda dependem apenas das redes sociais","Profissionais que precisam fortalecer autoridade","Negócios com site antigo, lento ou pouco claro","Projetos que desejam captar contatos e oportunidades"]'::jsonb, NULL, NULL, NULL, '[]'::jsonb),
('negocios-digitais', 'negocio', 'ecommerce', 'criacao-de-ecommerce', 'Solução digital', 'Criação de E-commerce', '/images/negocio-ecommerce.png', 'Uma loja online pronta para vender <em>no Brasil ou no mundo</em>.', 'Estrutura comercial, tecnológica e operacional para apresentar produtos, receber pagamentos e desenvolver vendas com segurança.', 'Uma loja online preparada para vender com segurança no mercado local, nacional ou internacional.', '["Loja completa, responsiva e fácil de navegar","Integração com meios de pagamento adequados","Estrutura pensada para gestão e crescimento"]'::jsonb, NULL, 'Conhecer', '/contato?assunto=projeto-ecommerce', '[]'::jsonb, 'Sua loja online facilita a compra — ou faz o cliente desistir antes do pagamento?', '["Um e-commerce não é apenas um catálogo. Ele precisa transmitir segurança, tornar a escolha simples e conduzir o cliente até a finalização da compra.","O projeto considera posicionamento, arquitetura de produtos, experiência de compra, pagamentos e preparação para campanhas."]'::jsonb, '[["01","Experiência de compra","Produtos organizados e caminhos claros até o checkout."],["02","Operação segura","Integrações adequadas ao mercado e ao modelo do negócio."],["03","Escalabilidade","Base preparada para ampliar produtos, regiões e campanhas."]]'::jsonb, '["Marcas que desejam iniciar vendas online","Lojas físicas em processo de digitalização","Empresas que querem vender nacionalmente","Projetos preparados para alcançar mercados internacionais"]'::jsonb, NULL, NULL, NULL, '[]'::jsonb),
('negocios-digitais', 'negocio', 'apps', 'apps-dedicados', 'Solução digital', 'Apps Dedicados', '/images/negocio-apps-dedicados.png', 'Transforme uma necessidade real em um aplicativo <em>seguro e escalável</em>.', 'Desenvolvimento sob medida para conectar sua ideia às pessoas, integrar processos e criar novas possibilidades de negócio.', 'Aplicações personalizadas para integrar processos, atender pessoas e criar novos modelos de negócio.', '["Solução desenhada para o problema do usuário","Integração com sistemas e processos existentes","Arquitetura preparada para segurança e evolução"]'::jsonb, NULL, 'Conhecer', '/contato?assunto=projeto-app-dedicado', '[]'::jsonb, 'Sua ideia precisa de um aplicativo — ou de uma solução digital capaz de produzir resultado?', '["Tecnologia sem propósito apenas transfere complexidade para uma nova tela. Um bom aplicativo nasce de um problema claro, de usuários reais e de objetivos mensuráveis.","Partimos do diagnóstico para definir funcionalidades, fluxos, integrações e etapas de desenvolvimento com visão de longo prazo."]'::jsonb, '[["01","Sob medida","Funcionalidades ligadas às necessidades do negócio."],["02","Integração","Conexão com dados, processos e sistemas adequados."],["03","Evolução","Base tecnológica preparada para novas etapas."]]'::jsonb, '["Empresas que precisam digitalizar processos próprios","Negócios com uma nova proposta de serviço","Projetos que exigem experiência móvel dedicada","Organizações que buscam eficiência e escala"]'::jsonb, NULL, NULL, NULL, '[]'::jsonb)
ON CONFLICT (slug) DO NOTHING;

SQL;

try {
    foreach (preg_split('/;\s*(?:\r?\n|$)/', $sql) as $statement) {
        if (trim($statement) !== '') $pdo->exec($statement);
    }
    $count = (int) $pdo->query('SELECT COUNT(*) FROM jd_catalog_items')->fetchColumn();
    echo "OK: tabela 'jd_catalog_items' pronta, coluna 'contacts.site' pronta.\n";
    echo "Itens no catálogo agora: {$count} (esperado: 14 na primeira execução).\n";
    echo "Acesse /admin/jd-catalog.php para conferir. Depois APAGUE este arquivo (migrate-jd-catalog.php).\n";
} catch (Throwable $e) {
    echo "ERRO: " . $e->getMessage() . "\n";
}
