<?php
require_once __DIR__ . '/_layout.php';
$entities=[
 'products'=>['label'=>'Produtos','category'=>'product_categories','fields'=>['title'=>'Título','slug'=>'Slug','summary'=>'Resumo','body'=>'Descrição completa','image_url'=>'URL da imagem','purchase_url'=>'Link de compra','cta_label'=>'Texto do botão','price'=>'Preço','status'=>'Status','featured'=>'Destaque']],
 'publications'=>['label'=>'Publicações','category'=>'publication_categories','fields'=>['title'=>'Título','slug'=>'Slug','excerpt'=>'Resumo','content'=>'Texto técnico','image_url'=>'URL da imagem','image_alt'=>'Texto alternativo da imagem','author_name'=>'Autor','seo_title'=>'Título SEO','seo_description'=>'Descrição SEO','status'=>'Status','published_at'=>'Data de publicação']],
 'blog_posts'=>['label'=>'Blog','category'=>'blog_categories','fields'=>['title'=>'Título','slug'=>'Slug','excerpt'=>'Resumo','content'=>'Texto do post','image_url'=>'URL da imagem','image_alt'=>'Texto alternativo da imagem','author_name'=>'Autor','seo_title'=>'Título SEO','seo_description'=>'Descrição SEO','status'=>'Status','published_at'=>'Data de publicação']],
 'contacts'=>['label'=>'Contatos','category'=>null,'fields'=>['name'=>'Nome','email'=>'E-mail','phone'=>'Telefone','subject'=>'Assunto','message'=>'Mensagem','status'=>'Status','internal_notes'=>'Notas internas']],
];
$entity=$_GET['entity']??'publications';if(!isset($entities[$entity])){$entity='publications';}$cfg=$entities[$entity];$action=$_GET['action']??'list';$pdo=db();$notice='';$error='';
function field_html(string $key,string $label,mixed $value,array $cfg): string { $v=h((string)$value);$isLong=in_array($key,['summary','body','excerpt','content','message','internal_notes','seo_description'],true);if($key==='status'){if($cfg['category']===null)return '<label>'.$label.'<select name="status"><option value="new"'.($v==='new'?' selected':'').'>Novo</option><option value="read"'.($v==='read'?' selected':'').'>Lido</option><option value="replied"'.($v==='replied'?' selected':'').'>Respondido</option><option value="archived"'.($v==='archived'?' selected':'').'>Arquivado</option></select></label>';return '<label>'.$label.'<select name="status"><option value="draft"'.($v==='draft'?' selected':'').'>Rascunho</option><option value="published"'.($v==='published'?' selected':'').'>Publicado</option><option value="archived"'.($v==='archived'?' selected':'').'>Arquivado</option></select></label>';}if($key==='featured'){return '<label>Exibir como destaque<select name="featured"><option value="0">Não</option><option value="1"'.($v==='1'?' selected':'').'>Sim</option></select></label>';}if($isLong)return '<label class="full">'.$label.'<textarea name="'.$key.'">'.$v.'</textarea></label>'; $type=$key==='email'?'email':($key==='price'?'number':'text');return '<label>'.$label.'<input type="'.$type.'" name="'.$key.'" value="'.$v.'"></label>'; }
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$postAction=$_POST['form_action']??'';$id=(int)($_POST['id']??0);try{if($postAction==='delete'&&$id){$pdo->prepare("DELETE FROM {$entity} WHERE id=?")->execute([$id]);$notice='Registro excluído.';}elseif(in_array($postAction,['create','update'],true)){$data=[];foreach($cfg['fields'] as $key=>$label){$data[$key]=trim((string)($_POST[$key]??''));}if($entity==='contacts'){if(!$data['name']||!filter_var($data['email'],FILTER_VALIDATE_EMAIL)||!$data['phone']||!$data['subject']||!$data['message'])throw new RuntimeException('Preencha nome, e-mail, telefone, assunto e mensagem.');}else{if(!$data['title']||!$data['slug'])throw new RuntimeException('Título e slug são obrigatórios.');$data['category_id']=(int)($_POST['category_id']??0)?:null;if(($data['status']??'')==='published'&&empty($data['published_at']))$data['published_at']=now_utc();if(isset($data['price']))$data['price']=$data['price']===''?null:$data['price'];}
if($postAction==='create'){$keys=array_keys($data);$pdo->prepare("INSERT INTO {$entity} (".implode(',',$keys).") VALUES (".implode(',',array_fill(0,count($keys),'?')).")")->execute(array_values($data));$notice='Registro cadastrado.';}else{$sets=implode(',',array_map(fn($k)=>"$k=?",array_keys($data)));$sets.=',updated_at=NOW()';$pdo->prepare("UPDATE {$entity} SET $sets WHERE id=?")->execute([...array_values($data),$id]);$notice='Registro atualizado.';}$action='list';} }catch(Throwable $e){$error=$e->getMessage();}}
admin_header($cfg['label']);if($notice):?><p class="notice"><?=h($notice)?></p><?php endif;if($error):?><p class="error"><?=h($error)?></p><?php endif;
if($action==='new'||($action==='edit'&&($id=(int)($_GET['id']??0)))){ $row=[];if($action==='edit'){$s=$pdo->prepare("SELECT * FROM {$entity} WHERE id=?");$s->execute([$id]);$row=$s->fetch()?:[];} $cats=$cfg['category']?$pdo->query("SELECT id,name FROM {$cfg['category']} WHERE is_active=1 ORDER BY sort_order,name")->fetchAll():[];?><section class="card"><h2><?=$action==='new'?'Novo':'Editar'?> registro</h2><form class="grid" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="form_action" value="<?=$action==='new'?'create':'update'?>"><input type="hidden" name="id" value="<?=h((string)($row['id']??''))?>"><?php if($cats):?><label>Categoria<select name="category_id"><option value="">Selecione</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>"<?=((string)($row['category_id']??'')===(string)$c['id'])?' selected':''?>><?=h($c['name'])?></option><?php endforeach;?></select></label><?php endif;foreach($cfg['fields'] as $key=>$label)echo field_html($key,$label,$row[$key]??($key==='status'?($entity==='contacts'?'new':'draft'):($key==='author_name'?'Global Invest Brasil':'')),$cfg);?><div class="full actions"><button>Salvar</button><a class="button light" href="/admin/manage.php?entity=<?=$entity?>">Cancelar</a></div></form></section><?php }else{$rows=$pdo->query("SELECT * FROM {$entity} ORDER BY id DESC")->fetchAll();?><div class="actions"><a class="button orange" href="/admin/manage.php?entity=<?=$entity?>&action=new">+ Cadastrar</a></div><section class="card table-wrap"><table><thead><tr><th>Registro</th><th>Status</th><th>Atualizado</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=h($r['title']??$r['name'])?></b><br><small><?=h($r['email']??$r['slug']??'')?></small></td><td><span class="badge"><?=h($r['status']??'—')?></span></td><td><?=h($r['updated_at']??$r['created_at']??'')?></td><td class="actions"><a class="button light" href="/admin/manage.php?entity=<?=$entity?>&action=edit&id=<?=$r['id']?>">Editar</a><form method="post" onsubmit="return confirm('Excluir este registro?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="form_action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="button danger">Excluir</button></form></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="4">Ainda não há registros.</td></tr><?php endif;?></tbody></table></section><?php }admin_footer();
